# Generated by Django 5.0.4 on 2024-04-13 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('username', models.CharField(default='raju', max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 20, 12, 21, 380616, tzinfo=datetime.timezone.utc))),
                ('full_name', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
    ]
