# Generated by Django 5.0.4 on 2024-04-13 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 20, 17, 8, 757392, tzinfo=datetime.timezone.utc)),
        ),
    ]
