# Generated by Django 5.0.4 on 2024-04-15 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 11, 53, 43, 136652, tzinfo=datetime.timezone.utc)),
        ),
    ]
